### ISSUE TITLE
Ability to easily set a specific repository

### ISSUE THREAD

**Issue by nmoinvaz** [neurolabusc/pigz-bench#4]
Right now the `pigz` directory gets wiped out every time I call `./1compile.sh` so if I want to test a particular branch of `zlib-ng` I can't because the repo specified in External-ZLIBng.cmake gets reset each time I run it.

**Comment by neurolabusc** [comment]
The current 1compile.sh script builds popular repositories. The subsequent test scripts will use each of the executables in the 'exe' folder. For developing custom versions of pigz, I would set the ZLIB_IMPLEMENTATION=Custom and set the ZLIB_ROOT to the location of your compiled zlib. You can then modify your zlib locally and just call the cmake/make/copy commands without having to download from the web.

```
git clone https://github.com/madler/pigz
cd pigz
mkdir build && cd build
cmake -DZLIB_IMPLEMENTATION=Custom -DZLIB_ROOT=/tst/zlib-ng-develop ..
make
#now copy resulting pigz to exe folder
```

**Comment by neurolabusc** [comment]
The new Python code makes this easier. 
 1. you can run this [a_compile.py](https://github.com/neurolabusc/pigz-bench-python/blob/master/a_compile.py) once to download and install the default builds. The pigz folder is not deleted.
 2. and then edit the a_compile.py script so it no longer downloads a new copy
 3. edit the cmake script for the fork/branch you want to build. For example, if you want to modify zlib-ng, you can edit `External-ZLIBng.cmake`, by default it installs the repository `github.com/zlib-ng/zlib-ng.git` and the branch `develop`
 4. Run the script again to create your own variants of pigz.

While not recommended, I also created the helper script [_a_compile_dynamic.py](https://github.com/neurolabusc/pigz-bench-python/blob/master/_a_compile_dynamic.py) which builds a dynamically linked version of pigz using your system's zlib. This could allow you to use [LD_PRELOAD](https://github.com/zlib-ng/zlib-ng) to select your library.
